// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6RAdL2uww_ptxgNzGwAcDG9Ryk9Gne_s',
    appId: '1:252775384238:web:a1e80a7504c625f852193f',
    messagingSenderId: '252775384238',
    projectId: 'crafty-furniture-95d1d',
    authDomain: 'crafty-furniture-95d1d.firebaseapp.com',
    storageBucket: 'crafty-furniture-95d1d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvuVrIErA2Zl4wCJlQFH7hO5AQB5-hMiY',
    appId: '1:252775384238:android:ed07876a641be06452193f',
    messagingSenderId: '252775384238',
    projectId: 'crafty-furniture-95d1d',
    storageBucket: 'crafty-furniture-95d1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBrwL6oYVE6ohPP7xZXhp-TfpkfwZYfjI',
    appId: '1:252775384238:ios:66f9fb022ece065452193f',
    messagingSenderId: '252775384238',
    projectId: 'crafty-furniture-95d1d',
    storageBucket: 'crafty-furniture-95d1d.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBrwL6oYVE6ohPP7xZXhp-TfpkfwZYfjI',
    appId: '1:252775384238:ios:66f9fb022ece065452193f',
    messagingSenderId: '252775384238',
    projectId: 'crafty-furniture-95d1d',
    storageBucket: 'crafty-furniture-95d1d.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6RAdL2uww_ptxgNzGwAcDG9Ryk9Gne_s',
    appId: '1:252775384238:web:74166d6772ed6fa252193f',
    messagingSenderId: '252775384238',
    projectId: 'crafty-furniture-95d1d',
    authDomain: 'crafty-furniture-95d1d.firebaseapp.com',
    storageBucket: 'crafty-furniture-95d1d.appspot.com',
  );
}
